spring:
  config:
    activate:
      on-profile: local
    import:
      - db-core.yaml
      - logging.yml
  application:
    name: hello-spring-api
logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: local-dev

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: staging


---
spring:
  config:
    activate:
      on-profile: live
